# Generated by Django 6.0.3 on 2026-03-27 14:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_is_deleted_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
